version: 2 # circle-ci 版本
jobs: # 任务
  build: # 构建
    docker: # 构建环境
      - image: circleci/node:10
    branches: 
      only:
        - master
    steps: # 步骤
      - add_ssh_keys:
          fingerprints:
            - "86:60:54:e1:b0:fc:0c:6b:a9:88:83:9b:bc:87:75:e1"          
      - checkout
      - echo 'A first hello' 
      - npm -v
      - run
          name: Install # 执行名称为 Install 的任务
          command: yarn install # 命令任务是安装项目中的依赖
      - run
          name: Build # 执行名称为 Build 的任务
          command: yarn build # 命令任务是打包构建


